# Generated by Django 5.2.5 on 2025-08-08 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('LANGUAGE', 'Programming Language'), ('FRAMEWORK', 'Framework/Technology'), ('DATABASE', 'Database'), ('CLOUD_DEVOPS', 'Cloud & DevOps'), ('SPECIALIZATION', 'Specialization')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('issuer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EngineerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('summary', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('availability', models.CharField(default='remote', help_text='remote | on-site | hybrid', max_length=64)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('certifications', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.certification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='profiles.engineerprofile')),
                ('technologies', models.ManyToManyField(blank=True, to='profiles.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.engineerprofile')),
                ('technologies', models.ManyToManyField(blank=True, to='profiles.skill')),
            ],
        ),
        migrations.CreateModel(
            name='EngineerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(default='Intermediate', help_text='Junior | Intermediate | Senior | Lead | Architect', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.engineerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
            ],
            options={
                'unique_together': {('profile', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='skills',
            field=models.ManyToManyField(related_name='profiles', through='profiles.EngineerSkill', to='profiles.skill'),
        ),
    ]
