# Generated by Django 5.2.5 on 2025-08-08 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='engineerprofile',
            options={'verbose_name': 'Profil Ingénieur', 'verbose_name_plural': 'Profils Ingénieurs'},
        ),
        migrations.AlterModelOptions(
            name='engineerskill',
            options={'verbose_name': 'Compétence Ingénieur', 'verbose_name_plural': 'Compétences Ingénieur'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Expérience', 'verbose_name_plural': 'Expériences'},
        ),
        migrations.AlterModelOptions(
            name='portfolioproject',
            options={'verbose_name': 'Projet de Portfolio', 'verbose_name_plural': 'Projets de Portfolio'},
        ),
        migrations.AlterField(
            model_name='certification',
            name='expires_on',
            field=models.DateField(blank=True, null=True, verbose_name='Expire le'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issued_on',
            field=models.DateField(blank=True, null=True, verbose_name='Délivrée le'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(max_length=100, verbose_name='Éditeur'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='availability',
            field=models.CharField(default='remote', help_text='remote | on-site | hybrid', max_length=64, verbose_name='Disponibilité'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.certification', verbose_name='Certifications'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=128, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='skills',
            field=models.ManyToManyField(related_name='profiles', through='profiles.EngineerSkill', to='profiles.skill', verbose_name='Compétences'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name="Années d'expérience"),
        ),
        migrations.AlterField(
            model_name='engineerskill',
            name='level',
            field=models.CharField(default='Intermédiaire', help_text='Junior | Intermédiaire | Senior | Lead | Architecte', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='engineerskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.engineerprofile', verbose_name='Profil'),
        ),
        migrations.AlterField(
            model_name='engineerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill', verbose_name='Compétence'),
        ),
        migrations.AlterField(
            model_name='engineerskill',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name="Années d'expérience"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=150, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.engineerprofile', verbose_name='Profil'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='profiles.skill', verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='profiles.engineerprofile', verbose_name='Profil'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='profiles.skill', verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('LANGUAGE', 'Langage de programmation'), ('FRAMEWORK', 'Framework/Technologie'), ('DATABASE', 'Base de données'), ('CLOUD_DEVOPS', 'Cloud & DevOps'), ('SPECIALIZATION', 'Spécialisation')], max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
    ]
