# Generated by Django 5.2.5 on 2025-08-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='specialized_profiles', to='profiles.skill', verbose_name='Spécialisations'),
        ),
    ]
