# Generated by Django 5.2.5 on 2025-08-08 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_certification_options_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Affectation', 'verbose_name_plural': 'Affectations'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'verbose_name': 'Jalon', 'verbose_name_plural': 'Jalons'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={'verbose_name': 'Exigence du projet', 'verbose_name_plural': 'Exigences du projet'},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={'verbose_name': 'Sprint', 'verbose_name_plural': 'Sprints'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='allocated_percentage',
            field=models.PositiveIntegerField(default=100, verbose_name='Pourcentage alloué'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_on',
            field=models.DateField(auto_now_add=True, verbose_name='Assigné le'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='profiles.engineerprofile', verbose_name='Ingénieur'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Terminé'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(verbose_name='Échéance'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='complexity',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée')], default='MEDIUM', max_length=10, verbose_name='Complexité'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, max_length=100, verbose_name='Domaine'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=128, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='project',
            name='remote_allowed',
            field=models.BooleanField(default=True, verbose_name='Télétravail autorisé'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='level',
            field=models.CharField(default='Intermédiaire', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='minimum_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Années minimales'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='projectrequirement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill', verbose_name='Compétence'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Objectif'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project', verbose_name='Projet'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(verbose_name='Date de début'),
        ),
    ]
